import {
  mdiAccountCircleOutline,
  mdiBullseyeArrow,
  mdiCalendarMultiselectOutline,
  mdiChartBar,
  mdiFilterRemoveOutline,
  mdiFoodAppleOutline,
  mdiMagnify,
  mdiMinusCircle,
  mdiNotebook,
  mdiPlusCircle,
  mdiSilverwareForkKnife,
  mdiWeatherNight,
  mdiWeatherSunny,
  mdiWeatherSunset,
  mdiWeatherSunsetUp,
  mdiWhiteBalanceSunny,
} from '@mdi/js';
import { aliases } from 'vuetify/iconsets/mdi-svg';

export default {
  ...aliases,
  account: mdiAccountCircleOutline,
  notebook: mdiNotebook,
  forkKnife: mdiSilverwareForkKnife,
  chart: mdiChartBar,
  calendar: mdiCalendarMultiselectOutline,
  plusCircle: mdiPlusCircle,
  minusCircle: mdiMinusCircle,
  weatherNight: mdiWeatherNight,
  weatherBalanceSunny: mdiWhiteBalanceSunny,
  weatherSunUp: mdiWeatherSunsetUp,
  weatherSunSet: mdiWeatherSunset,
  weatherSunny: mdiWeatherSunny,
  bullseyeArrow: mdiBullseyeArrow,
  apple: mdiFoodAppleOutline,
  magnify: mdiMagnify,
  filterRemove: mdiFilterRemoveOutline,
};
